### ISSUE TITLE
_ans is not set

### ISSUE THREAD

**Issue by goFrendiAsgard** [goFrendiAsgard/chimera-framework#1]
## Expected Behavior
The default `out` of a chain should be `_ans`

## Current Behavior
Sometime a chain has no default `out`

## Possible Solution
Add preprocessing for single command

## Steps to Reproduce (for bugs)
1. Create this file:
   ```
   # test.chiml
   do:
     # build docker image
    - |docker build -t chimera-db -f chimera-db.dockerfile .
   ```
2. Run `sudo chimera test.chiml`

## Context
I try to build docker image for chimera-cms

## Your Environment
* Version used: 0.7.4
* Environment name and version: node 8.10.0
* Operating System and version: ubuntu 17.0
* Link to your project: [chimera-cms](https://github.com/goFrendiAsgard/chimera-cms)

**Comment by goFrendiAsgard** [comment]
Solved in https://github.com/goFrendiAsgard/chimera-framework/commit/4e89e0d070ad56b7137a95807fbb49248a6fd2f1

**Comment by jozuafp** [comment]
Where can I find the rationale for this project?

**Comment by goFrendiAsgard** [comment]
sorry, what do you mean by rationale?
